# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HvweBLHNawokFMh7Qm8wC0R3m9ftjXRE
"""

import hashlib

def obtenerHash(cadena):
    return hashlib.sha256(cadena.encode('utf-8')).hexdigest()
def crearRaizDeMerkle(listaHojas):

    if listaHojas is None:
        return 0
    nivelActual = []

    for hoja in listaHojas:
        nivelActual.append(obtenerHash(hoja))

    while len(nivelActual)>1:
        nivelSiguiente = []

        if len(nivelActual) % 2 != 0:
            nivelActual.append(nivelActual[-1])

        for i in range(0, len(nivelActual), 2):
            hashCombinado = nivelActual[i] + nivelActual[i+1]
            hashPadre = obtenerHash(hashCombinado)
            nivelSiguiente.append(hashPadre)
        nivelActual = nivelSiguiente
    return nivelActual[0]

def validarHojaDirecta(hoja, listaHojas, posicionHoja, raizEsperada):
    #Hecho con IA...
    es_la_misma_hoja = (listaHojas[posicionHoja] == hoja)
    raiz_valida = (crearRaizDeMerkle(listaHojas) == raizEsperada)

    return es_la_misma_hoja and raiz_valida


listaHojas = ["Carlos le envió 1500 pesos a Ana",
    "Beatriz le envió 300 pesos a David",
    "Elena le envió 5000 pesos a Fernando",
    "Gabriela le envió 1200 pesos a Hugo",
    "Isabel le envió 750 pesos a Javier"]
validarHojaDirecta("Elena le envió 500 pesos a Fernando",listaHojas,2,crearRaizDeMerkle(listaHojas))